FILENAMES = [
    # "index.md",
    # "communication_encryption.md",
    # "installation_guide.md",

    # "technical_documentation/voting_terminal.md",
    # "technical_documentation/voting_terminal/installation.md",
    # "technical_documentation/gateway.md",
    # "technical_documentation/gateway/installation.md",
    # "technical_documentation/gateway/state_vector.md",
    # "technical_documentation/gateway/synchronization_service.md",
    # "technical_documentation/gateway/token_manager.md",
    # "technical_documentation/gateway/token_writer.md",
    # "technical_documentation/gateway/voting_process_manager.md",
    # "technical_documentation/gateway/voting_service.md",
    # "technical_documentation/server.md",
    # "technical_documentation/server/installation.md",
    # "technical_documentation/server/modules/database.md",
    # "technical_documentation/server/modules/seeding.md",
    # "technical_documentation/server/modules/voting.md",
    # "technical_documentation/server/modules/statistics.md",
    # "technical_documentation/statistic_application.md",

    # "gateway/synchronization_service.md",
    # "gateway/token_manager.md",
    # "gateway/token_writer.md",
    # "gateway/voting_process_manager.md",
    # "gateway/voting_service.md",
    # "server.md",
    # "server/installation.md",
    # "server/modules/database.md",
    # "server/modules/seeding.md",
    # "server/modules/voting.md",
    # "server/modules/statistics.md",
]