FILENAMES = [
    "gateway.md",
    "gateway/state_vector.md",
    "gateway/synchronization_service.md",
    "gateway/token_manager.md",
    "gateway/token_writer.md",
    "gateway/voting_process_manager.md",
    "gateway/voting_service.md",
    "server.md",
    "server/instalation.md",
    "server/modules/database.md",
    "server/modules/seeding.md",
    "server/modules/voting.md",
    "server/modules/statistics.md",
]