FILENAMES = [
    "index.md",
    "communication_encryption.md",
    "installation_guide.md",

    # "technical_documentation/voting_terminal.md",
    # "technical_documentation/voting_terminal/installation.md",
    # "technical_documentation/gateway.md",
    # "technical_documentation/gateway/installation.md",
    # "technical_documentation/gateway/state_vector.md",
    # "technical_documentation/gateway/synchronization_service.md",
    # "technical_documentation/gateway/token_manager.md",
    # "technical_documentation/gateway/token_writer.md",
    # "technical_documentation/gateway/voting_process_manager.md",
    # "technical_documentation/gateway/voting_service.md",
    # "technical_documentation/server.md",
    # "technical_documentation/server/installation.md",
    # "technical_documentation/server/modules/database.md",
    # "technical_documentation/server/modules/seeding.md",
    # "technical_documentation/server/modules/voting.md",
    # "technical_documentation/server/modules/statistics.md",
    # "technical_documentation/statistic_application.md",

    # "user_guide/voting_terminal.md",
    # "user_guide/voting_terminal/party_choose.md",
    # "user_guide/voting_terminal/candidates_choose.md",
    # "user_guide/voting_terminal/vote_submit.md",
    # "user_guide/gateway.md",
    # "user_guide/gateway/elections.md",
    # "user_guide/gateway/nfc_tags_managment.md",
    # "user_guide/gateway/synchronization.md",
    # "user_guide/gateway/voting_terminals.md",
    # "user_guide/gateway/report.md",
    # "user_guide/gateway/contact.md",
    # "user_guide/stats_app.md",
    # "user_guide/stats_app/filtering.md",
    # "user_guide/stats_app/party_results.md",
    # "user_guide/stats_app/candidates_results.md",
    # "user_guide/stats_app/slovakia_map.md",
    # "user_guide/stats_app/parliament_map.md",
    # "user_guide/stats_app/regional_results.md",
    # "user_guide/stats_app/general_stats.md",
]