name: Docs Stage

on:
  push:

  workflow_dispatch:

jobs:
  stage:
    name: Docs Stage on team server
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker Build and Stage
        run: docker-compose -f .staging/docker-compose.yml up -d --build
